### ISSUE TITLE
Igreja e não Ingreja

### ISSUE THREAD

**Issue by luisangelorjr** [Moonslate/MFoMT#1]
Opa!
Baixei e  estou jogando essa versão pt-br com minha namorada.

Percebemos esse erro.
Eu poderia alterar e mandar um pr, mas não sei que programa e configs vc utiliza para alterar os textos (abri no vsCode aqui)

Se puder passar as infos para te ajudar a revisar, ficarei grato.
Se não, vou abrindo issues para o que for achando

**Comment by luisangelorjr** [comment]
Aliás, vlw pelo trampo <3

**Comment by andrey-moura** [comment]
> 
> 
> Opa!
> Baixei e estou jogando essa versão pt-br com minha namorada.
> 
> Percebemos esse erro.
> Eu poderia alterar e mandar um pr, mas não sei que programa e configs vc utiliza para alterar os textos (abri no vsCode aqui)
> 
> Se puder passar as infos para te ajudar a revisar, ficarei grato.
> Se não, vou abrindo issues para o que for achando

Muito obrigado por avisar pelo erro. Usei a ferramenta de busca de texto e não encontrei a palavra "Ingreja". Provavelmente já foi corrigido. Já faz muito tempo que não atualizo a ROM que está no site.
> 
> 
> Aliás, vlw pelo trampo <3

De nada :+1:
